name : pytest
on : 
    workflow_dispatch
jobs:
    job-1:
        runs-on : ubuntu-latest
        steps:
            - uses: actions/setup-node@v6
            - run: uv sync
    job-2: 
        needs: job-1
        runs-on: ubuntu-latest
        steps:
            - run: uv run python -m scripts/tests/test_classifiers.py
            - run: uv run python -m scripts/tests/test_ingestion.py
            




