name : pytest
on : 
    workflow_dispatch
jobs:
    job-1:
        runs-on : ubuntu-latest
        steps:
            - uses: actions/setup-node@v6
            - run: uv sync
    job-2: 
        needs: job-1
        runs-on: ubuntu-latest
        steps:
            - run: uv run python -m scripts.data.download_nltk
            - run: uv run python -m scripts.data.download
    job-3:
        needs: job-2
        runs-on: ubuntu-latest
        steps:
            - run: uv run python -m scripts.train.train
            - run: uv run python -m scripts.train.evaluate --model baseline
            
    job-4:
        needs: job-3
        runs-on: ubuntu-latest
        steps:
            - run: uv run python -m scripts.train.tuning
            - run: uv run python -m scripts.train.evaluate --model tuned
                    
            




