name: pytest

on:
  workflow_dispatch:

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: pip install uv 

      - name: Install dependencies
        run: uv sync

      - name: Download NLTK data
        run: uv run python -m scripts.data.download_nltk

      - name: Download data
        run: uv run python -m scripts.data.download

      - name: Train baseline model
        run: uv run python -m scripts.train.train

      - name: Evaluate baseline model
        run: uv run python -m scripts.train.evaluate --model baseline

      - name: Tune model
        run: uv run python -m scripts.train.tuning

      - name: Evaluate tuned model
        run: uv run python -m scripts.train.evaluate --model tuned

            




